name: "CI for Pseudocode"
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
